swagger : "2.0"
info:
  version: "1.0.0"
  title: "MovieDatabase"
  description: "Application for Movie Actors Directors and series"
host : "localhost:3010"
basePath: /
schemes: 
  - "http"
consumes:
  - "application/json"
produces: 
  - "application/json"
paths:  
  /admin:
    get:
      summary: "Get all administrators"
      description: "Returns a list containing all admins."
      responses:
        200:
          description: " A list of all Admins"
          schema:
            type: "array"
            items:
              required:
                - "username"
              properties:
                username:
                  type: "string"
                email:
                  type: "string"
                phonenumber:
                  type: "string"
  /admin/{id}:
    get:
      summary: "Gets a admin by their ID"
      description: "Returns a single admin for its id"
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "The admin's ID"
          type: "integer"
      responses:
        200:
          description: "A Admin by ID"
          schema:
            required:
              - "id"
            properties:
              username:
                type: "string"
              email:
                type: "string"
              phonenumber:
                type: "string"
        404:
          description: "The Admin does not exists."
  /admin/sing-up:
    post:
      summary: "Create a new Admin"
      description: "Creating a new admin"
      parameters:
        - name: "username"
          in: "path"
          required: true
          description: "username"
          type: "string"
        - name: "email"
          in: "path"
          required: true
          description: "email"
          type: "string"
        - name: "phonenumber"
          in: "path"
          required: true
          description: "phonenumber"
          type: "string"
        - name: "password"
          in: "path"
          required: true
          description: "minimum 8 letter, one specieal caracter and one number"
      responses:
        200:
          description: "Created new admin"
          schema:
            required:
              - "id"
            properties:
              username:
                type: "string"
              email:
                type: "string"
              phonenumber:
                type: "string"
              password: 
                type: "string"
        404:
          description: "Admin allready exists"
    

     

